### ISSUE TITLE
Cannot move released class under a class that is not released

### ISSUE THREAD

**Issue by soimugeoWB** [who-icatx/icatx-project#228]
As a user i want to be able to move a released class in the class hierarchy under a class that is not yet released.

**Comment by soimugeoWB** [comment]
fixed move of released class. However the move will not be made if current parent is equivalent class. this is how it was implemented in the MoveEntityChangeListGenerator, maybe to avoid cycles?

**Comment by tudorache** [comment]
I think the only restriction we have with respect to moving released classes is that released classes cannot be moved under a retired ancestor (basically in a retired branch). Otherwise, I think we can move it anywhere in the hierarchy.

"However the move will not be made if current parent is equivalent class. this is how it was implemented in the MoveEntityChangeListGenerator, maybe to avoid cycles?"
- If it is a move (meaning removing the equivalent parent), then, yes, it should not be possible.
However, if it is an "add parent" operation, we can allow it, as long as the parent is not in a retired branch.

@soimugeoWB Please review also #30 and #38 and close them if they are done.

**Comment by csnyulas** [comment]
I think that what this issue is about (the inability to move a released class under a non-released class) is resolved, so we can close this issue. There is still a problem with the refresh (see #224), especially when moving (with DnD or by Editing parents) a released class and/or a class with multiple parents, but that should be dealt with separately.
