### ISSUE TITLE
Postcoordination axis value selection in Logical Definition tab might be confusing

### ISSUE THREAD

**Issue by csnyulas** [who-icatx/icatx-project#259]
In the **Logical Definition** tab, to specify a value for a specific postcoordination axis, we need to select first the axis (from the dropdown list appearing in the "Axis" column), and then a value for that axis, by clicking on the plus button in the "Value" column. The possible values shown in the popup dialog are restricted according to the value selected for the axis.

However, currently it is possible to click on the plus button for the value selection, even if there was nothing previously selected for the axis. In this case the popup dialog will be empty and the user might be confused why it is so. 

<img width="938" height="464" alt="Image" src="https://github.com/user-attachments/assets/ed043db1-94d0-4dec-8abd-4615fe3a9649" />

<img width="1119" height="526" alt="Image" src="https://github.com/user-attachments/assets/86da5c01-119f-4458-870c-15db04ba5159" />

To avoid this situation, we should disable the plus button until a value is selected for the axis. We could even add a tooltip to the plus button saying either:
- "Select a value for the .... axis", in case the axis is already selected, replacing "..." with the name of the axis, or
- "Please select a postcoordination axis first", for the disabled plus button, while the axis value is not yet set.

**Comment by alexsilaghi** [comment]
fixed in https://github.com/protegeproject/webprotege-gwt-ui/pull/204/files

**Comment by csnyulas** [comment]
I tested this and at first it seemed to be working. However I found two cases where the problem still occurs:
- in the "Necessary Conditions" section
- once the axis was set to something and after that it was reset to the empty value (showing the placeholder "Select axis" text)

I observed that the suggested tooltip was not added either. I am not sure if this was because it was too complicated or because you forgot about it.

Can you please take a look and fix this @alexsilaghi ? I'll set the status of this issue to "In Progress" until then.

**Comment by csnyulas** [comment]
I'll close this as there is a follow-up #282 that is dealing with the problem at the selection of values for an unspecified axis.
Also, the suggestion for making smarter tooltips on the "Plus" button, is not something trivial, if I remember correctly what @alexsilaghi said.
